### PR TITLE
Adds HMR support

### PR DESCRIPTION
**Pull request by ekhaled**
This PR adds full HMR support to this plugin.

However @DeMoorJasper, I cannot make the tests pass on node 6.

I have tried with `require.resolve()` like we did it [here](https://github.com/sveltejs/svelte-loader/blob/master/index.js#L6-L12). 
But then it cannot resolve absolute paths at all. And even HMR does not work.

Right now HMR works perfectly, but the tests fail.

Not too familiar with parcel, hope you can help in this regard.

### CODE REVIEW

**Comment by DeMoorJasper** [comment]
Awesome! CI is reporting some weird errors though, not sure why, seems like a broken npm. Although it should normally not even use npm but yarn.

**Comment by ekhaled** [comment]
`Refusing to install package with name "parcel-plugin-svelte" under a package also called "parcel-plugin-svelte"`

It's because of this line https://github.com/DeMoorJasper/parcel-plugin-svelte/pull/21/commits/1f99af838ea52515a3c9f29ae68d7adb3b9bff63#diff-e09eee290ae64f6517e6bc6c77f68c59R10

I have mentioned above that I tried using `require.resolve` to mitigate that (like we do in the webpack loader). But then parcel refuses to resolve absolute paths

**Comment by DeMoorJasper** [comment]
@ekhaled You could inline them, would also be faster

**Comment by DeMoorJasper** [comment]
Yeah, didn't keep in mind hoisting in case of a lot of components this could kinda be in issue, although this is only dev mode doesn't really matter in this case.

**Comment by DeMoorJasper** [comment]
I think that actually fixed it :)
The tests are still failing though, as the dep tree isn't correct in the tests

**Comment by ekhaled** [comment]
You can merge this in if you like, as it is working in terms of the user side of things.

This will not work if you have a svelte based package `npm link`-ed.

I'll try and see if I can get the main issue fixed at a later stage. 
The main issue being parcel refuses resolve absolute paths.

**Comment by DeMoorJasper** [comment]
Wait what? Parcel can resolve absolute paths I've merged that a lil while back. And in requires it's been there for a couple releases already

**Comment by ekhaled** [comment]
in that case you are the right person to understand whats going on here :)

If I replace `require('parcel-plugin-svelte/lib/hot-api')` with `require('${require.resolve('./hot-api')}')`  it doesn't work. here: https://github.com/DeMoorJasper/parcel-plugin-svelte/pull/21/files#diff-e09eee290ae64f6517e6bc6c77f68c59R8

**Comment by DeMoorJasper** [comment]
Ow require.resolve doesn’t work, that’s correct

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ekhaled** [comment]
require.resolve spits out an absolute path. That's why I thought parcel can't resolve them.

Do you know what's going on here? Or have any workarounds in mind?

**Comment by DeMoorJasper** [comment]
Oh shit yeah I guess this is a parcel bug.

I'll create a workaround for now, seems to be fairly easy to do as we can calculate the relative path to the asset

**Comment by DeMoorJasper** [comment]
Alright found a way around this, will close this PR in favor of #22 

Could you have a look at #22 to make sure everything is in there? :)

**Pull request closed without merging**
